W-16375669  Automate updating of custom functions in migrated IP & DR
salesforcecli/plugin-omnistudio-migration-tool pull request #241
Opened 2024-09-12 08:17 UTC by girjeshshakya

### What does this PR do?
this replaces the old custom formula syntax to standard formula syntax for custom implementation.
for example : 
REPLACE(targetString, replacementString). ===> FUNCTION(“CustomStringFunctions”, “replace”, targetString, replacementString).

2024-09-12 10:26 UTC, AbhinavKumar-sf requested changes
Please write Unit test cases

2024-09-16 08:24 UTC, girjeshshakya commented
> Please write Unit test cases

added the unit tests

2024-09-16 09:20 UTC, AbhinavKumar-sf commented on src/migration/dataraptor.ts
Can we fix this large diff

2024-09-16 09:20 UTC, AbhinavKumar-sf commented on src/migration/dataraptor.ts
> +        if (drItem[this.namespacePrefix + 'Formula__c'] != null) {
Let's catch the error, error in updating one drItem shouldn't impact other 
Also put logging for each item processing

2024-09-16 09:20 UTC, AbhinavKumar-sf commented on src/migration/omniscript.ts
> +            if (ipElement[`${this.namespacePrefix}PropertySet__c`] != null) {
Shouldn't we read specific key's value of  PropertySet__c and update that rather than searching and replacing in entire PropertySet config, also explore if you can move this inside **mapElementData** method.

please add logging and error handling

2024-09-16 10:52 UTC, ankitakumar04 approved these changes

2024-09-25 09:38 UTC, girjeshshakya commented
> Please write Unit test cases

Added

2024-09-25 09:40 UTC, girjeshshakya commented on src/migration/omniscript.ts
> +            if (ipElement[`${this.namespacePrefix}PropertySet__c`] != null) {
added error handling and logging.
and for inside IP it is not possible to know where the formula is being configured, so this is the only way for parse and replace the formula syntax.

2024-09-25 11:52 UTC, AbhinavKumar-sf approved these changes

2024-10-03 08:59 UTC, merged